### ISSUE TITLE
Maven Central

### ISSUE THREAD

**Issue by brianm** [krukow/clj-ds#1]
I'd like to be able to use this library more conveniently from other libraries, but that means (in practice) putting it in maven central.

I'd be happy to do one of the following:

1) Convert the build to maven

or 

2) Maintain a package in maven central (which I'll do by maintaining a mavenized version, same code, slightly diff roject layout and add a pom)

**Comment by krukow** [comment]
Please do, I'll happily support it.

**Comment by krukow** [comment]
Actually did you mean this as a question? If so, please convert the build to maven.

**Comment by brianm** [comment]
Meant as a question yes. Pull request for maven build incoming.

To be able to actually push releases into maven central you will need to create the accounts and so on as specified at

https://docs.sonatype.org/display/Repository/Sonatype+OSS+Maven+Repository+Usage+Guide

I'll send a pull request with the pom set up for it.

**Comment by krukow** [comment]
https://issues.sonatype.org/browse/OSSRH-3283
