### ISSUE TITLE
IPersistent* interfaces

### ISSUE THREAD

**Issue by donnerpeter** [krukow/clj-ds#14]
Hi,

what's the idiomatic way of creating a set of some elements, checking if the set contains something and iterating over it? I've run into a couple issues there:
1. IPersistenSet.cons returns IPersistentCollection, and it's impossible to call contains without casting.
2. IPersistentSet doesn't implement Iterable, explicit casting required here as well.

Is it by design, or something to fix? The first issue would be fixed very easily, the second one is trickier as APersistentSet and APersistentTrie (both implementing IPersistentSet) would have to have different Iterable type parameters.

**Comment by stanislas** [comment]
Hi,

Sorry for the late answer.
The best is to use the classes and interfaces in clj_ds and not in clj_lang. The clj_lang package contains the core classes from the clojure runtime and there are difficult to use in Java directly (casting and co like you noticed).

I created the classes and interfaces in clj_ds to wrap the clj_lang part. It is not complete yet, if functionality is not present, feel free to tell me.
Answers to your questions:
-  creating a set : Persistents.hashSet(1, 2, 3)
- "adding" an element to a set: PersistentSet#plus
- clj_ds.PersistentSet implements java.util.Set. (#contains and implements Iterable).

Does this help you?
Cheers ,stan.

**Comment by donnerpeter** [comment]
Yes, this helps me, thanks! It wasn't obvious that IPersistentSet shouldn't be used at all.
