### ISSUE TITLE
Newer API; less cruft

### ISSUE THREAD

**Issue by grignaak** [krukow/clj-ds#15]
I've been working on removing a lot of the cruft from the code. Things that aren't needed like the entire huge RT class, a lot dead code in the implementation.

While I am at it, I've been moving towards an api NOT designed by a compiler writer ;)

Please take a look and let me know what you think! 

https://github.com/grignaak/clj-ds/tree/java-api

**Comment by krukow** [comment]
Looks interesting!
Are you planning on creating a pull request at some time?

**Comment by jedwards1211** [comment]
@grignaak looks nice, just an aside, I prefer keeping the names `PersistentMap` etc. instead of `Dictionary` to be consistent with java collection names

**Comment by grignaak** [comment]
My team (several years ago) decided to rewrite this; we ended up with a completely different API and implementations. We used it a bunch internally, and I am now refactoring it out into its own library: [cow-collections](https://github.com/grignaak/cow-collections).

I have it in Beta right now as I continue to move the code over to github and make sure the artifacts and such all make sense.

**Comment by krukow** [comment]
OK - thanks for the update. I'll close this.
