### ISSUE TITLE
Empty PersistentList can not be instantiated 

### ISSUE THREAD

**Issue by anuj919** [krukow/clj-ds#6]
I am not able to use

PersistentList<Integer> empty = PersistentList.emptyList()

as it gives following error 

required: PersistentList<Integer>
found:    <T>IPersistentList<T>
where T is a type-variable:
  T extends Object declared in method <T>emptyList()

I am not able to fix this in the source. Can you please fix this?

**Comment by krukow** [comment]
The way Clojure is programmed leads to many methods delared to return interfaces not concrete classes.

is there any reason you don't do:

IPersistentList l = PersistentList.emptyList();

**Comment by anuj919** [comment]
Oops.. my bad. Couldn't find how to instantiate list initially.

Thanks.
